# Generated by Django 4.2.9 on 2024-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='код верификации'),
        ),
    ]
