# Generated by Django 5.0 on 2024-08-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='дата начала рассылки')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания рассылки')),
                ('period', models.CharField(blank=True, choices=[('разовая', 'разовая'), ('ежедневная', 'ежедневная'), ('еженедельная', 'еженедельная'), ('ежемесячная', 'ежемесячная')], max_length=255, null=True, verbose_name='периодичность')),
                ('status', models.CharField(blank=True, choices=[('создана', 'создана'), ('отправлена', 'отправлена'), ('отменена', 'отменена')], default='создана', max_length=255, null=True, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='название рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
