# Generated by Django 5.0 on 2024-08-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active'),
        ('mailing', '0002_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='finish',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='period',
        ),
        migrations.AddField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, null=True, verbose_name='периодичность'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликована'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(related_name='messages', to='clients.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='связанное сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='draft', max_length=20, null=True, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=150, verbose_name='тема письма'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время последней попытки')),
                ('attempt_status', models.CharField(blank=True, choices=[('success', 'Успешно'), ('failed', 'Неуспешно')], max_length=15, null=True, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, max_length=255, null=True, verbose_name='ответ сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('attempt_status',),
            },
        ),
    ]
