# Generated by Django 5.0 on 2024-08-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_finish_mailing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='send_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок сообщения'),
        ),
    ]
